version: '3.3'

services:

  web:
   image: sammlerio/web-dev
   container_name: web
   ports:
     - "4200:4200"
   volumes:
     - ./src:/opt/web/src
     - ./proxy.conf.json:/opt/web/proxy.conf.json
   depends_on:
     - mongo

  mongo:
    image: mongo:3.4.7
    container_name: mongo
    ports:
      - "27017:27017"
    logging:
        driver: none

  auth-service:
    image: sammlerio/auth-service
    container_name: auth-service
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=development
      - PORT=3010
      - JWT_SECRET=foo
      - MONGODB_DEBUG=false
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
    depends_on:
      - mongo

  log-service:
    image: sammlerio/log-service
    container_name: log-service
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
    depends_on:
      - mongo


