ARG NODE_VER="10.24.1"
ARG PORT=4200

FROM node:${NODE_VER}

ENV HOME_DIR "opt/web"

RUN mkdir -p $HOME_DIR
WORKDIR $HOME_DIR

COPY package.json angular.json tsconfig.json proxy.conf.json ./

RUN npm config set loglevel warn
RUN npm install --quiet --no-package-lock

COPY . /opt/web

ENV PORT=${PORT}
EXPOSE $PORT

CMD ["npm", "run", "start"]
