version: '3.3'

services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    logging:
        driver: none

  mongo-seed:
    image: sammlerio/mongo-seed
    container_name: mongo-seed
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
    volumes:
      - ./config/db-seed:/data
    command: [
      "mongoimport --host mongo --port 27017 --db sammlerio --mode upsert --type json --file /data/auth-service~~user.json --jsonArray"
    ]

  nats-streaming:
    image: nats-streaming
    ports:
      - "4222:4222"
      - "4223:4223"
      - "8223:8223"
      - "8222:8222"
    volumes:
      - ./.datastore:/datastore
    command: [
      "-m", "8222",
      "--store", "FILE",
      "--dir", "datastore"
    ]

  web:
   image: sammlerio/web-dev
   container_name: web
   ports:
     - "4200:4200"
   volumes:
     - ./src:/opt/web/src
     - ./proxy.conf.json:/opt/web/proxy.conf.json
   depends_on:
     - mongo

  auth-service:
    image: sammlerio/auth-service
    container_name: auth-service
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=development
      - PORT=3010
      - JWT_SECRET=foo
      - AUDIT_LOG=true
      - MONGODB_DEBUG=false
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=sammlerio
      - NATS_STREAMING_HOST=nats-streaming
      - NATS_STREAMING_PORT=4222
    depends_on:
      - mongo
      - nats-streaming

  audit-log-service:
    image: sammlerio/audit-log-service
    container_name: audit-log-service
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=sammlerio
      - NATS_STREAMING_HOST=nats-streaming
      - NATS_STREAMING_PORT=4222
    depends_on:
      - mongo
      - nats-streaming


